# Site
repository: truejulosdu13/julesschleinitz.github.io
favicon: images/favicon.ico
google_site_verification: CoIqeZeNoqA_Ggf3RbR3XPdg3jLHzjsdP-yrwMCJmcA
# Content configuration version
version: 2

# Personal info
name: Jules Schleinitz
title: PhD Student - Mechanistic Studies
email: jules.schleinitz@ens.psl.eu
#address : ENS Paris, Office E021, 24 rue Lhomond 75005 Paris, France #(https://www.google.com/maps/place/D%C3%A9partement+de+Physique,+Ecole+Normale+Sup%C3%A9rieure/@48.8422093,2.3429802,17z/data=!4m12!1m6!3m5!1s0x47e671e99512085d:0x3b69748ca3b78f0d!2s%C3%89cole+Normale+Sup%C3%A9rieure!8m2!3d48.8422058!4d2.3451689!3m4!1s0x0:0x5f69605cfbac8f02!8m2!3d48.8430845!4d2.3466789)
# website: www.github.com/truejulosdu13.github.io/julesschleinitz.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  truejulosdu13
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: julesschleinitz
linkedin_username: jules-schleinitz-90a5a1161
# strava_username: 27486196
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: strava
  icon: fab fa-strava
  url: https://www.strava.com/athletes/27486196
- title: chimie.ens.fr/grimaud/
  icon: fas fa-flask
  url: https://www.chimie.ens.fr/grimaud/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: ""

# About Section
# about_title: About Me
about_profile_image: images/bike_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jules and I'm a PhD Student in Chemistry working at [Ecole Normale Supérieure](https://www.chimie.ens.fr/en/chemistry-department-of-ens/) in Paris under the supervision of [Laurence Grimaud](https://www.chimie.ens.fr/grimaud/current-team/team-leaders/laurence-grimaud/). I use a combination of experimental and theoretical tools to understand chemical reaction pathways. Among them **XRD**, **UV-visible**, **IR**, **EPR**, and **NMR** spectroscopies as well as **electrochemistry** and theoretical tools : **DFT** and **Machine Learning**.
  Alongside with my research activities, I spend half of my time teaching chemistry at Ecole Normale Supérieure (Organic chemistry : lessons, electrochemistry : tutorials and experimental sessions, experimental projects for bachelor and master students.).
  
  Here a short [CV](/julesschleinitz.github.io/CV_v3.pdf).

content:
  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Organic Chemistry - Lessons
        #link: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf
        #link_text: Nomenclature en chimie organique2
        #additional_links:
        #  - title:  Stereochimie et Analyse Conformationnelle
        #    icon: fab fa-github
        #    url: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          There are for sure some mistakes in the lessons and exercices files, please let me know when noticed ! 
        description: | # this will include new lines to allow paragraphs
          The lessons are written in French for students applying to the [Agrégation externe de physique chimie option physique](https://agregation-physique.org/).
          
          Cours :
           - [Nomenclature en chimie organique](/julesschleinitz.github.io/organic_chemistry_lessons/Cours1.pdf)
           - [Stéréochimie](/julesschleinitz.github.io/organic_chemistry_lessons/Cours2.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_1.pdf) 
           - [Substitution nucléophile bimoléculaire - **S<sub>N</sub>2**](/julesschleinitz.github.io/organic_chemistry_lessons/Cours3.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_2.pdf)
           - [Substitution nucléophile unimoléculaire - **S<sub>N</sub>1**](/julesschleinitz.github.io/organic_chemistry_lessons/Cours4.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_3.pdf)
           - [Réactions d'éliminations - **E<sub>1</sub>** et **E<sub>2</sub>**](/julesschleinitz.github.io/organic_chemistry_lessons/Cours5.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_5.pdf)
           - [Organomagnésiens](/julesschleinitz.github.io/organic_chemistry_lessons/Cours6.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_6.pdf)
           - [Additions nucléophiles - **A<sub>N</sub>**](/julesschleinitz.github.io/organic_chemistry_lessons/Cours7.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_7.pdf)
           - [Additions éliminations - **A<sub>N</sub> + E**](/julesschleinitz.github.io/organic_chemistry_lessons/Cours8.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_8.pdf)
           - [Oxydo réduction de l'alcool à l'acide](/julesschleinitz.github.io/organic_chemistry_lessons/Cours9.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_9.pdf)
           - [Réaction en &alpha; d'un groupe électro-attracteur](/julesschleinitz.github.io/organic_chemistry_lessons/Cours10.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_10.pdf)
           - [I  - Réactivité de liaison double apolaire : les Alcènes](/julesschleinitz.github.io/organic_chemistry_lessons/Cours11.pdf), [Fiche Résumé](/julesschleinitz.github.io/organic_chemistry_lessons/take_away_cours_11.pdf)
           - [II - Réactivité de liaison double apolaire : les Alcènes ](/julesschleinitz.github.io/organic_chemistry_lessons/Cours12.pdf)
           - [Catalyse hétérogène et homogène](/julesschleinitz.github.io/organic_chemistry_lessons/Cours13.pdf)
           - [Polymères en chimie organique](/julesschleinitz.github.io/organic_chemistry_lessons/Cours14.pdf)
           
           Exercices et Corrigés :
           - [Stéréochimie](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_1_Stereochimie.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_Stéréochimie.pdf)
           - [**S<sub>N</sub>2**](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_2_SN2.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_SN2.pdf)
           - [**S<sub>N</sub>2** & **S<sub>N</sub>1**](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_3_SN1-SN2.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_SN.pdf)
           - [**E<sub>1</sub>** & **E<sub>2</sub>**](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_4_E.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_E.pdf)
           - [Organomagnésiens](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_5_RMgX.pdf), Corrigé
           - [**A<sub>N</sub>**](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_AN.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_AN.pdf)
           - [**A<sub>N</sub> + E**](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_AN+E.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_AN+E+ex1-8.pdf)
           - [Alcènes](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_Alcenes_I.pdf), Corrigé
           - [Diels Alder](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_DA.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_lessons/Corrigé_DA_2.pdf)
           - [Réactivité en &alpha; d'un groupe electro attracteur](/julesschleinitz.github.io/organic_chemistry_exercices/Ex_reactivite_alpha.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/Corrigé_reactivité_alpha.pdf)
           
           Devoir Maison et Corrigés :
           - [DM_1](/julesschleinitz.github.io/organic_chemistry_exercices/DM1_phys.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/DM1_phys_corrige.pdf)
           - [DM_2](/julesschleinitz.github.io/organic_chemistry_exercices/DM2_phys.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/DM2_phys_corr.pdf)
           - [DM_3](/julesschleinitz.github.io/organic_chemistry_exercices/DM3_phys.pdf), [Corrigé](/julesschleinitz.github.io/organic_chemistry_exercices/DM3_phys_corr.pdf) 
   
      - layout: top-middle
        title: Electrochemistry - Tutorials
        #link: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf
        #link_text: Nomenclature en chimie organique2
        #additional_links:
        #  - title:  Stereochimie et Analyse Conformationnelle
        #    icon: fab fa-github
        #    url: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          There are for sure some mistakes in the tutorials and correction files, please let me know when noticed ! 
        description: | # this will include new lines to allow paragraphs
          Cours Introductif :
          [Slides](/julesschleinitz.github.io/electrochemistry_tutorials/Cours_Introductif.pdf)
          
          
          Tutorials  :
          - [Mesure du potentiel de charge nulle](/julesschleinitz.github.io/electrochemistry_tutorials/TD_1_jules.pdf), [Corrigé](/julesschleinitz.github.io/electrochemistry_tutorials/TD_1_jules_corrige.pdf)
          - [Modelisation d'une interface electrochimique](/julesschleinitz.github.io/electrochemistry_tutorials/TD_2_Randless.pdf), [Corrigé](/julesschleinitz.github.io/electrochemistry_tutorials/TD_2_Full_corrige.pdf)
          - [Buttler-Volmer & Application](/julesschleinitz.github.io/electrochemistry_tutorials/TD_2_BV.pdf), [Corrigé](/julesschleinitz.github.io/electrochemistry_tutorials/TD_demo_ButlerVolmer.pdf)
          - [Marcus & Application](/julesschleinitz.github.io/electrochemistry_tutorials/TD_2_Marcus.pdf), [Corrigé](/julesschleinitz.github.io/electrochemistry_tutorials/TD_2_Full_corrige.pdf)
          - [Limitation par le **transfert de masse**](/julesschleinitz.github.io/electrochemistry_tutorials/TD_3_jules.pdf), [Corrigé]()
          - [Determination du nombre d'electrons](/julesschleinitz.github.io/electrochemistry_tutorials/TD_4_determination_nombre_electrons.pdf), [Corrigé](/julesschleinitz.github.io/electrochemistry_tutorials/TD_4_corrigé.pdf)


          Practical courses  :
          - [Introduction to voltamperometry techniques](/julesschleinitz.github.io/electrochemistry_tutorials/TP1_v2.pdf)
          - [Determination of the number of electrons involved in the reduction of benzophenone in ethanol](/julesschleinitz.github.io/electrochemistry_tutorials/TP_2_det_electrons.pdf)

          
          Some references I highly recommand :
          - Basic Concepts : [A Practical Beginner’s Guide to Cyclic Voltammetry, *J. Chem. Educ.* **2018**, 95, 2, 197–206](https://pubs.acs.org/doi/abs/10.1021/acs.jchemed.7b00361)
          - Advanced Applications : [A synthetic chemist's guide to electroanalytical tools for studying reaction mechanisms, *Chem. Sci.*, **2019**,10, 6404-6422](https://pubs.rsc.org/en/content/articlelanding/2019/sc/c9sc01545k)
          - The Bible : *Elements of Molecular and biomolecular Electrochemistry*, **J.-M. Savéant**, 2006
          - *Electrochimie physique et analytique*, **Hubert H. Girault**, 2013

                      
  - title: Research Projects & Collaborations # Title for the section
    layout: list # Type of content section (list/text)
    content:
#      - layout: left
#        title: ML for Reaction Yield Prediction
        #link: boringcompany.com
        # link_text: boringcompany.com
#        sub_title: theoretical study
#        caption: January 2021 - Present
#        quote: >
#          To be continued
#        description: | # this will include new lines to allow paragraphs
#            How precise can we predict the yield of a reaction with ML trained on a noisy dataset ?
            
#      - layout: left
#        title: O.A. of Nitro compounds on Palladium Complexes
        #link: boringcompany.com
        # link_text: boringcompany.com
#        sub_title: experimental and DFT study
#        caption: September 2020 - Present
#        quote: >
#          To be continued
#        description: | # this will include new lines to allow paragraphs
#            What make the O.A. on PDI-NO<sub>2</sub> substrate so easy compared to nitro benzene ?
      - layout: top-middle
        title: Collaborators
       # caption: 2010 - 2013
       # sub_title: BSc Computer Science
       # quote: >
       #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - [Maxime Vitale](https://www.chimie.ens.fr/grimaud/current-team/team-leaders/maxime-r-vitale/)
          - [Maximilien Levesque](https://www.linkedin.com/in/maxlvsq/?originalSubdomain=fr)
          - [Ilaria Ciofini](https://www.chimieparistech.psl.eu/wp-content/uploads/2021/02/ilariaciofini-notice-biographique.pdf)
          - [Sami Lakhdar](https://lhfa.cnrs.fr/index.php/en/component/contact/contact/165?Itemid=797)
          - [Marine Desage-El Murr](http://marinedesageelmurr.fr/)
          - [Rodolphe Villeumier](https://www.chimie.ens.fr/recherche/laboratoire-pasteur/chimie-theorique/members-of-the-theoretical-chemistry-group/rodolphe-vuilleumier/)
          - [Maxime Langevin](https://www.linkedin.com/in/maxime-langevin-1aa58912b/?originalSubdomain=fr)
          - [Anna Perfetto](https://www.linkedin.com/in/anna-perfetto-2a2a55143/?originalSubdomain=fr)
          - [Sylvestre Bachollet](https://www.linkedin.com/in/sylvestre-bachollet-50783042/?originalSubdomain=fr)

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
       # title: Harvard University
       # caption: 2010 - 2013
       # sub_title: BSc Computer Science
       # quote: >
       #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          [3] **A hybrid bioinspired catechol-alloxazine triangular nickel complex stabilizing protons and electrons**
          
          Agnideep Das,   Hannah Jobelius,   **Jules Schleinitz**,   Stefani Gamboa-Ramírez,   Geordie Creste,   Gwendal Kervern,   Jesus Raya,   Nolwenn Le Breton,   Aurélie Guenet,   Zahia Boubegtiten,   Laurence Grimaud,   Maylis Orio,   Guillaume Rogez,   Petra Hellwig,   Sylvie Choua,   Sylvie Ferlay  and  Marine Desage-El Murr  
          
          *Inorganic Chemistry Frontiers*, **2021**, 8, 5286-5298. [DOI: 10.1039/D1QI01131F](https://pubs.rsc.org/en/content/articlelanding/2021/qi/d1qi01131f/unauth), PDF


          [2] **Metal-Free Deoxygenation of Amine N-Oxides: Synthetic and Mechanistic Studies**
          
          W. Lecroq, **J. Schleinitz**, M. Billoue, A. Perfetto, A-C. Gaumont, J. Lalevée, I. Ciofini, L. Grimaud, S. Lakhdar
          
          *ChemPhysChem*, **2021**, 22, 1237. [DOI: 10.1002/cphc.202100108](https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cphc.202100108), [PDF](https://hal.archives-ouvertes.fr/hal-03306177/file/ChemPhysChem%20%28final%20rev%20version%29%281%29.pdf)
          
          
          [1] **Bis-Cyclooctatetraenyl Thulium(II): Highly Reducing Lanthanide Sandwich Single-Molecule Magnets**
          
          J. Moutet, **J. Schleinitz**, L. La Droitte, M. Tricoire, F. Pointillart, F. Gendron, T. Simler, C. Clavaguéra, B. Le Guennic, O. Cador, G. Nocton
          
          *Angewandte Chemie International Edition*, **2021**, 60 (11), 6042-6046. [DOI: 10.1002/anie.202015428](https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.202015428), [PDF](https://hal.archives-ouvertes.fr/hal-03163652/document)
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in chemistry, physics and teaching, I am passionated by cycling, I love hiking and any kind of exploration in nature. I enjoy playing soccer on rainy sundays and share a beer after.
      I am from Marseille and no doubt that it is the best city in the World! Of course, I support the [Olympique de Marseille](https://www.om.fr/fr) soccer team.

      <img src="images/bonne_mere.png" alt="Paris" style="width:100%;" class="center">  
    #  ![La bonne mère](images/bonne_mere.png)

# Footer
footer_show_references: true
# references_title:  (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
