# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jules Schleinitz
title: PhD Student - Inorganic Mechanism Investigation
email: jules.schleinitz@ens.psl.eu
website: www.github.com/truejulosdu13.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  truejulosdu13
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: julesschleinitz
linkedin_username: jules-schleinitz-90a5a1161
# strava_username: 27486196
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: strava
  icon: fab fa-strava
  url: https://www.strava.com/athletes/27486196
- title: chimie.ens.fr/grimaud/
  icon: fas fa-flask
  url: https://www.chimie.ens.fr/grimaud/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/bike_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jules and I'm a PhD Student in Chemistry working at [Ecole Normale Supérieure](https://www.chimie.ens.fr/en/chemistry-department-of-ens/) in Paris under the supervision of [Laurence Grimaud](chimie.ens.fr/grimaud/current-team/team-leaders/laurence-grimaud/). I use a combination of experimental and theoretical tools to understand chemical reaction pathways. Among them **XRD**, **UV-visible**, **IR**, **EPR**, and **NMR** spectroscopies as well as **electrochemistry** and theoretical tools : **DFT** and **Machine Learning**.
  Alongside with my research activities, I spend half of my time teaching chemistry at Ecole Normale Supérieure (Organic chemistry : lessons, electrochemistry : tutorials and experimental sessions, experimental projects...).

content:
  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Organic Chemistry - Lessons
        #link: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf
        #link_text: Nomenclature en chimie organique2
        #additional_links:
        #  - title:  Stereochimie et Analyse Conformationnelle
        #    icon: fab fa-github
        #    url: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The lessons are written in French for students applying to the [Agrégation externe de physique chimie option physique](https://agregation-physique.org/).
          
          Cours :
           - [Nomenclature en chimie organique](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf)
           - [Stéréochimie](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf)
           - [Substitution nucléophile bimoléculaire - **S<sub>N</sub>2**](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours3.pdf)
           - [Substitution nucléophile unimoléculaire - **S<sub>N</sub>1**](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours4_v2.pdf)
           - [Réactions d'éliminations - **E<sub>1</sub>** et **E<sub>2</sub>**](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours5.pdf)
           - [Organomagnésiens](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours6.pdf)
           - [Additions nucléophiles - **A<sub>N</sub>**](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours7.pdf)
           - [Additions éliminations - **A<sub>N</sub> + E**](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours8.pdf)
           - [Oxydo réduction de l'alcool à l'acide](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours9.pdf)
           - [Réaction en &alpha; d'un groupe électro-attracteur](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours10.pdf)
           - [I  - Réactivité de liaison double apolaire : les Alcènes](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours11.pdf)
           - [II - Réactivité de liaison double apolaire : les Alcènes ](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours12.pdf)
           - [Catalyse hétérogène et homogène](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours13.pdf)
           - [Polymères en chimie organique](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours14.pdf)
           
           Exercices et Corrigés :
           - 
           - 
           
           Devoir Maison et Corrigés :
           -
           -
   
   
      - layout: top-middle
        title: Electrochemistry - Tutorials
        #link: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf
        #link_text: Nomenclature en chimie organique2
        #additional_links:
        #  - title:  Stereochimie et Analyse Conformationnelle
        #    icon: fab fa-github
        #    url: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Tutorials and correction :
          - blablabla
          -
          
          Some references I highly recommand for beginners and more in electrochemistry :

                      
  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ML for Yield Prediction
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: theoretical study
        caption: January 2021 - Present
        quote: >
          To be continued
        description: | # this will include new lines to allow paragraphs
            How precise can we predict the yield of a reaction with ML trained on a noisy dataset ?
            
      - layout: left
        title: O.A. of Nitro compounds on Palladium Complexes
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: experimental and DFT study
        caption: September 2020 - Present
        quote: >
          To be continued
        description: | # this will include new lines to allow paragraphs
            What make the O.A. on PDI-NO<sub>2</sub> substrate so easy compared to nitro benzene ?

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
       # title: Harvard University
       # caption: 2010 - 2013
       # sub_title: BSc Computer Science
       # quote: >
       #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          [2] **Metal-Free Deoxygenation of Amine N-Oxides: Synthetic and Mechanistic Studies**
          
          W. Lecroq, **J. Schleinitz**, M. Billoue, A. Perfetto, A-C. Gaumont, J. Lalevée, I. Ciofini, L. Grimaud, S. Lakhdar
          
          *ChemPhysChem*, **2021**, 22, 1237. [DOI: 10.1002/cphc.202100108](https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cphc.202100108), [PDF]()
          
          
          [1] **Bis-Cyclooctatetraenyl Thulium(II): Highly Reducing Lanthanide Sandwich Single-Molecule Magnets**
          
          J. Moutet, **J. Schleinitz**, L. La Droitte, M. Tricoire, F. Pointillart, F. Gendron, T. Simler, C. Clavaguéra, B. Le Guennic, O. Cador, G. Nocton
          
          *Angewandte Chemie International Edition*, **2021**, 60 (11), 6042-6046. [DOI: 10.1002/anie.202015428](https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.202015428), [PDF](https://hal.archives-ouvertes.fr/hal-03163652/document)
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in chemistry and physics and teaching, I am passionated by cyclism, I love hiking and any kind of exploration in nature. I enjoy playing soccer on rainy sundays and share a beer after.
      I am from Marseille and no doubt that it is the best city in the World! Of course, I support the Olympique de Marseille soccer team.

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
