# Site
title: Jules Schleinitz
email: jules.schleinitz@ens.psl.eu
description: >- # this means to ignore newlines until "baseurl:"
  A guide to getting started with Jekyll.
  
# repository: truejulosdu13/julesschleinitz.github.io
# favicon: images/android-chrome-512x512.png
baseurl: "julesschleinitz.github.io"
url: https://truejulosdu13.github.io # the base hostname & protocol for your site, e.g. http://example.com
domain: truejulosdu13.github.io
google_site_verification: CoIqeZeNoqA_Ggf3RbR3XPdg3jLHzjsdP-yrwMCJmcA
# Content configuration version
# version: 2

# Dark Mode (true/false/never)
# darkmode: false

# Social links
# twitter_username: facespics
github_username:  truejulosdu13
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: julesschleinitz
linkedin_username: jules-schleinitz-90a5a1161
# strava_username: 27486196
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-7116-4772


# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM
  
#plugins:
# - jekyll-seo-tag
