# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jules Schleinitz
title: PhD Student - Inorganic Mechanism Investigation
email: jules.schleinitz@ens.psl.eu
website: www.github.com/truejulosdu13.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  truejulosdu13
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: julesschleinitz
linkedin_username: jules-schleinitz-90a5a1161
# strava_username: 27486196
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: strava
  icon: fab fa-strava
  url: https://www.strava.com/athletes/27486196
- title: chimie.ens.fr/grimaud/
  icon: fas fa-flask
  url: https://www.chimie.ens.fr/grimaud/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/bike_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jules and I'm a PhD Student in Chemistry working at [Ecole Normale Supérieure](https://www.chimie.ens.fr/en/chemistry-department-of-ens/) in Paris under the supervision of [Laurence Grimaud](chimie.ens.fr/grimaud/current-team/team-leaders/laurence-grimaud/). I use a combination of experimental and theoretical tools to understand chemical reaction pathways. Among them RXD, UV-visible, IR, EPR, and NMR spectroscopies as well as electrochemistry and theoretical tools : DFT and Machine Learning.  

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Organic Chemistry Lessons
        #link: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf
        #link_text: Nomenclature en chimie organique2
        #additional_links:
        #  - title:  Stereochimie et Analyse Conformationnelle
        #    icon: fab fa-github
        #    url: https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
            
           L'ensemble des cours de chimie organique traités pendant l'année sont donnés ci-dessous :
           - [Nomenclature en Chimie Organique](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours1.pdf)
           - [Stéréochimie](https://truejulosdu13.github.io/organic_chemistry_lessons/Cours2.pdf)
           - 
           
           Exercices et Corrigés
           - 
           - 
           
           Devoir Maison et Corrigés
           -
           -
           
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
       # title: Harvard University
       # caption: 2010 - 2013
       # sub_title: BSc Computer Science
       # quote: >
       #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          [2] Metal-Free Deoxygenation of Amine N-Oxides: Synthetic and Mechanistic Studies
          
          W. Lecroq, J. Schleinitz, M. Billoue, A. Perfetto, A-C. Gaumont, J. Lalevée, I. Ciofini, L. Grimaud, S. Lakhdar
          
          Chemphyschem. 2021 Jun 16;22(12):1237-1242. [doi: 10.1002/cphc.202100108](https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cphc.202100108) [PDF]()
          
          
          [1] Bis-Cyclooctatetraenyl Thulium(II): Highly Reducing Lanthanide Sandwich Single-Molecule Magnets
          
          J. Moutet, J. Schleinitz, L. La Droitte, M. Tricoire, F. Pointillart, F. Gendron, T. Simler, C. Clavaguéra, B. Le Guennic, O. Cador, G. Nocton
          
          Angewandte Chemie International Edition, Wiley-VCH Verlag, 2021, 60 (11), pp.6042-6046. [doi: 10.1002/anie.202015428](https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.202015428) [PDF](https://hal.archives-ouvertes.fr/hal-03163652/document)
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in chemistry and physics, I am passionated by cyclism, I love hiking and any kind of exploration in nature. I enjoy playing soccer with 

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
